### ISSUE TITLE
Reporte: Apertura > Asociado a Campo tipo Botón

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/frontend-core#109]
En la definición de diccionario de aplicación de una ventana pueden existir botones en los que están asociados reportes:

1. Abrir la ventana de `Reportes Financieros`.
2. Clic en el botón `Crear Informe`.

### GIF

https://user-images.githubusercontent.com/20288327/170617920-3c3dcb56-f618-4495-97b9-fb3bc4886a3e.mp4

**Comment by EdwinBetanc0urt** [comment]
En la intefaz de Vue se pueden diferenciar los botones que tienen reportes asociados ya que presentan el icono de un informe dentro del botón.

https://user-images.githubusercontent.com/20288327/170617746-3a04983e-8624-48f3-9336-bf7156bda356.mp4

**Comment by niclopup** [comment]
No se puede verificar debido a que no se puede abrir una ventana correctamente. entiendo que esto está a la espera de las correcciones en las ventanas

![image](https://user-images.githubusercontent.com/31936815/175373922-cc1fcf5a-6b14-42e2-b0d7-8bbda02cb5c9.png)


![image](https://user-images.githubusercontent.com/31936815/175373823-338b7df9-faf8-433f-a5d2-1c8d06406090.png)

**Comment by EdwinBetanc0urt** [comment]
@niclopup ya disponible en las ventanas:


https://user-images.githubusercontent.com/20288327/178772782-3b074ada-a274-4c43-9d3b-f3a941da9ed9.mp4
