### ISSUE TITLE
Formulario: Conciliación de Estado de Cuenta > Procesar Movimientos.

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/frontend-core#1317]
Enviar el resultado, desde la tabla de importación `I_BankStatement` hacia la ventana de `Estado de Cuenta` (`C_BankStatement`).

**Comment by niclopup** [comment]
No se logra replicar esto en nuestra instancia de testing 24144

por favor necesitamos resolver esto para poder utilizar la funcionalidad.

Adjunto GIF mostrando el problema que pasé por discord el 30/08/2023

![Prueba_Conciliacion_estado_de_cuentas_no_encuentra_concidencia_en_VUE_si_en_ZK](https://github.com/solop-develop/frontend-core/assets/31936815/2c87208e-3388-4973-ab30-8efd723064df)

**Comment by niclopup** [comment]
Se procesa correctamente creando las líneas que debe crear (no el resultado que muestra que son más líneas) 

pero una vez procesado, debería cerrar la ventana y queda quieto en la misma conciliación bancaria dando lugar a la duda si terminó ok o no.

El msj al terminar debería dar más información de que nro de conciliación fue la que se agregaron cuantas líneas.
Además en el msj agregaría la aclaración que se agregarón X cantidad de línas con coincidencia y Z cantidad sin coincidencia.

![Match entre Movimiento y Pago y creación de Bankstatementline](https://github.com/solop-develop/frontend-core/assets/31936815/064fc2be-d89e-4a27-a52c-ba7d9a8fcb3f)
