### ISSUE TITLE
Error SB: Al Crear DxP desde Orden de Compra desde SB se va el registro

### ISSUE THREAD

**Issue by niclopup** [solop-develop/frontend-core#2242]
## Bug report

Al Crear DxP desde Orden de Compra desde SB se va el registro luego de procesar el SB. 

#### Steps to reproduce

1. Crear DxP
2. Abrir SB Crear desde Orden/Recepción y seleccionar una línea de OC y procesar.
3. se cierra el SB y se va el registro de DxP que estabamos creando mostrando nuevamente el registro que aparecía al abrir la ventana antes de crear el DxP en cuestión.

#### Screenshot or Gif（截图或动态图）

![Al Crear DxP desde Orden de Compra desde SB se va el registro](https://github.com/solop-develop/frontend-core/assets/31936815/c8c0e2fb-3f86-4257-95bd-187816493f4b)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

![image](https://github.com/solop-develop/frontend-core/assets/31936815/f378c803-ef08-4923-a34d-ded2255f105c)

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.9.4

https://github.com/solop-develop/frontend-core/assets/78000356/34ae1c36-c2b8-419b-b76c-81429aecd459

**Comment by niclopup** [comment]
Me volvió a pasar esto en la ventana de "Recepción de Productos". 

Los pasos realizados fueron los siguientes:

1. Crear Orden de Compra
2. abrir ventana Recpeción de productos
3. Dar nuevo, completar los datos y guardar registro.
4. Click en Botón "Create from Orden/RMA". Abre SB de Crear desde, se selecciona Crear desde "Orden". Se selecciona la orden con 2 líneas. Se procesa ok
5. Al mostrar la ventana de Recepción de Productos, ya no muestra e registro que estaba parado sino que muestra el registro q mostró originalmente cuando abri la ventana.

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la version del front: https://github.com/solop-develop/frontend-core/releases/tag/4.4.023

https://github.com/user-attachments/assets/f27415c6-7724-49d6-bb24-8028690f319f

**Comment by niclopup** [comment]
sigue fallando. 

los pasos realizados para verificarlo fue:

1. Generar OC
2. Abrir ventana de Recepción y Generar Recepción con SB Crear Desde seleccionando la OC.
3. Abrir ventana Documentos por Pagar, Guardar documento definiendo SDN (DxC 1001501). 
4. Se abre el SB de Crear desde, se selecciona la oC 10913 y se procesa el SB.
5. Se vuelve a la ventana mostrando otro registro y no el que estaba creando.

![Image](https://github.com/user-attachments/assets/8970576b-4db2-41cc-9c9c-e41f0e31fb19)

el registro que estaba creando era:
![Image](https://github.com/user-attachments/assets/14540088-5bb1-4ba6-b21a-6b202dcabcde)

**Comment by niclopup** [comment]
el error persiste

https://github.com/user-attachments/assets/22ec73f9-716d-45aa-83bf-9c9eb392a7ee

viendo tu ejemplo, la validación la hicieron con una ventana donde ya tiene inicialmente filtrado sólo 1 documento... si se va a otro regiustro puede ser que por eso esté limitado a que no haya otro al cuál irse.

en el ejmplo que les paso se ve claramente que se sigue yendo a un registro diferente luego de que se selecciona una línea de orden para crear desde.

**Comment by elsiosanchez** [comment]
https://github.com/user-attachments/assets/fb348b7b-4b7e-440a-a0ab-fbb09063fdb9
